### ISSUE TITLE
spec2 dependency missing

### ISSUE THREAD

**Issue by P3trur0** [auth0-community/auth0-scala-samples#26]
Looking at [test source code](https://github.com/auth0-community/auth0-scala-samples/blob/8655042ab41c5eaee9f8daaffac654e78f65a983/00-Starter-Seed/regular-webapp/test/IntegrationSpec.scala) I see that this project should depend from specs2, however it seems that no dependency has been added to sbt.

Are you considering to improve this part?

If so, I'd propose to replace specs2 with ScalaTest and to align the unit tests properly.

**Comment by beardaway** [comment]
Hey there!

Terribly sorry for such delay in response! At the time the tool hosted in the repo was developed we didn't have enough bandwidth to implement it further that's why we kinda decided to "outsource" it to our community developers.

For now we are gradually expanding the team and we're aiming that at some point in the future we'll be able to maintain and develop this repo more effectively. Sorry for any inconvenience!
